config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:<br>
  <% @book.errors.full_messages.each do |message| %>
    ・<%= message %>
  <% end %>
<% end %>

<%= form_with model: @book, local:true do |f| %>
  <h6>Title</h6>
    <%= f.text_field :title %>
    <h6>Body</h6>
    <%= f.text_area :body %><br>
    <%= f.submit "Update Book" %>
<% end %>

<%= link_to "Show", book_path(@book) %>
  |
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h2>Books</h2>
  <% @books.each do |book| %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book_path(book), method: :delete %></td>
      </tr>
    </tbody>
  </table>
  <% end %>

<h4>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:<br>
  <% @book.errors.full_messages.each do |message| %>
    ・<%= message %><br>
  <% end %>
<% end %>

<div class="form">
  <%= form_with model: @book, local:true do |f| %>
    <h6>Title</h6>
    <%= f.text_field :title %>
    <h6>Body</h6>
    <%= f.text_area :body %><br>
    <%= f.submit "Create Book" %>
  <% end %>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
   
<table class="table">
  <tr>
    <td>Title:</td>
    <td><%= @book.title %></td>
  </tr>
  <tr>
    <td>Body:</td>
    <td><%= @book.body %></td>
  </tr>
</table>

<%= link_to "Edit", edit_book_path(@book) %>
  |
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>
  Bookersでは、さまざまな書籍に関するあなたの意見や<br>
  印象を共有し交換することができます<br>
  <%= link_to "start", books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>